name: Changeset Bot

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  changeset-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v23
        with:
          base_sha: ${{ github.event.pull_request.base.sha }}
          sha: ${{ github.event.pull_request.head.sha }}

      - name: Create comment with changed files
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const changedFiles = ${{ steps.changed-files.outputs.all_changed_files }};
            const fileList = changedFiles.split(' ').join('\n- ');
            const body = `이 PR에서 수정된 파일 목록 (${github.event.pull_request.base.ref} 브랜치 기준):\n\n- ${fileList}`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
